### PR TITLE
chain: fix NeutrinoClient segfault on NotifyReceived call

### LINKED ISSUE #819: NeutrinoClient data race
## Problem
The `NeturinoClient` `Rescan` method locks, sets `rescan` to `nil` then unlocks itself before resetting the value.
As the client state is `scanning = true` yet `rescan = nil` when the lock is released there is a race between the executing `Rescan` method and any `NotifyReceived` calls that are waiting to obtain the lock.  If a `NotifyReceived` call picks up the lock in this state, it will panic when it tries to run `rescan.Update` as `scanning` is `true`.

https://github.com/btcsuite/btcwallet/blob/master/chain/neutrino.go#L351

__Originally analyzed and found by @guggero in https://github.com/lightningnetwork/lnd/issues/6985__

```
--- FAIL: TestLightningWallet (7.74s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d47b7]

goroutine 6 [running]:
testing.tRunner.func1.2({0x9c34e0, 0xfdbfe0})
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1399 +0x39f
panic({0x9c34e0, 0xfdbfe0})
	/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/panic.go:884 +0x212
github.com/lightninglabs/neutrino.(*Rescan).Update(0x0, {0xc00064a248, 0x1, 0xc00129a4e0?})
	/home/runner/work/go/pkg/mod/github.com/lightninglabs/neutrino@v0.14.2/rescan.go:1391 +0x57
github.com/btcsuite/btcwallet/chain.(*NeutrinoClient).NotifyReceived(0xc0000fa120, {0xc0012bc060?, 0x1, 0x1})
	/home/runner/work/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.1/chain/neutrino.go:457 +0x159
github.com/btcsuite/btcwallet/wallet.(*Wallet).NewAddress(0xc0001ce480, 0x0, {0x0?, 0x9f16e0?})
	/home/runner/work/go/pkg/mod/github.com/btcsuite/btcwallet@v0.16.1/wallet/wallet.go:3020 +0x17a
github.com/lightningnetwork/lnd/lnwallet/btcwallet.(*BtcWallet).NewAddress(0xc0005a8180, 0x50?, 0x0, {0xa88a60?, 0x7?})
	/home/runner/work/lnd/lnd/lnwallet/btcwallet/btcwallet.go:556 +0x10c
github.com/lightningnetwork/lnd/lnwallet/test.loadTestCredits(0xc000078720, 0xc000340380, 0x14, 0x0?)
	/home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:275 +0x287
github.com/lightningnetwork/lnd/lnwallet/test.createTestWallet({0xc00031ff80?, 0xa87ad1?}, 0x5?, 0xfe8080, {0xc43560, 0xc0001ca180}, {0xc48820, 0xc0005a8180}, {0xc43b00, 0xc0011c41c8}, ...)
	/home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:378 +0x4a9
github.com/lightningnetwork/lnd/lnwallet/test.runTests(_, _, {_, _}, _, {{0xc00002eba0, 0xe}, {0xa873bc, 0x2}, {0xa879c6, ...}, ...}, ...)
	/home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:3398 +0x2633
github.com/lightningnetwork/lnd/lnwallet/test.TestLightningWallet(0xc000007ba0, {0xa89361, 0x8})
	/home/runner/work/lnd/lnd/lnwallet/test/test_interface.go:3064 +0x8ef
github.com/lightningnetwork/lnd/lnwallet/test/neutrino_test.TestLightningWallet(0x0?)
	/home/runner/work/lnd/lnd/lnwallet/test/neutrino/neutrino_test.go:12 +0x25
testing.tRunner(0xc000007ba0, 0xb9f9b8)
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.0/x64/src/testing/testing.go:1493 +0x35f
FAIL	github.com/lightningnetwork/lnd/lnwallet/test/neutrino	7.770s
FAIL
```

### Related Work

See PR #695
See PR #533

## Solution 1
Make a change against `btcwallet` to address the state management issues:
1. make the entire `Rescan` method a critical path (i.e., only unlock via a single defer call)
2. make the entire `NotifyReceived` method a critical path
3. remove the locking in the `notificationHandler` to prevent a deadlock caused by making `Rescan` completely critical.  This locking isn't necessary as it attempts to read the state of the `rescanErr` channel.  But if `rescanErr` is nil, then there is no `Rescan` object created yet so no errors to read.  Also, reading from a `nil` channel will simply block but the read is wrapped in a select statement with other exits.

### Risks
- there are no unit tests on the neutrino client in btcwallet and even a targeted change like this is hard to know if it introduced any regressions

### PR DESCRIPTION
**Pull request by MStreet3**
Fixes #819
Replaces #820

### Background

There is datarace in the neutrino client implementation that is causing test
flakes in `lnd`. The shared `rescan` object and the granular
locking strategy allow for the possibility of a segmentation fault when
`NotifyReceived` attempts to call `Update` on a `rescan` that is `nil`.  This
is because the `clientMtx` lock is released after `rescan` is set to `nil`.

### Changes

The solution here is to be minimally invasive.  Add a new `rescanMtx` mutex
and require that the `NotifyReceived` method and the `Rescan` method
hold the `rescanMtx` lock for the duration of their execution.  Locking and
unlocking of the client is unaffected and changes to the `rescan` object
become atomic.

### Testing

This PR adds two interfaces `rescanner` and `nutrinoChainService`
to abstract out the dependency on structs from the `neutrino` package.

This PR adds a file of mock implementations for these interfaces and uses them
in a new unit test file.

### CODE REVIEW

File: chain/internal/rescan/rescan.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package rescan
+
+import "github.com/lightninglabs/neutrino"
+
+type Updater interface {
```
Comment (guggero) [inline chain/internal/rescan/rescan.go:7]: Nice to extract those out into an interface. Though I don't think we need an extra sub package. If we want to make them internal, we just don't export them (so `rescanUpdater`, `rescanStarter`, `rescan` as names).

Also, all interfaces should get Godoc comments to explain what they represent.

File: chain/neutrino.go [hunk 2]
```diff
@@ -14,6 +14,7 @@ import (
 	"github.com/btcsuite/btcd/rpcclient"
 	"github.com/btcsuite/btcd/txscript"
 	"github.com/btcsuite/btcd/wire"
+	"github.com/btcsuite/btcwallet/chain/internal/rescan"
```
Comment (guggero) [inline chain/neutrino.go:17]: Importing this package as `rescan` will cause some variables that are called the same to become shadowing. One more reason to not add those interfaces to a new sub package.

File: chain/neutrino.go [hunk 3]
```diff
@@ -48,6 +48,8 @@ type NeutrinoChainService interface {
 	PeerByAddr(string) *neutrino.ServerPeer
 }
 
+var _ NeutrinoChainService = (*neutrino.ChainService)(nil)
```
Comment (guggero) [inline chain/neutrino.go]: This can be done in the commit that introduces the interface.

File: chain/mocks_test.go [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+	"github.com/btcsuite/btcd/chaincfg"
+	"github.com/btcsuite/btcd/chaincfg/chainhash"
+	"github.com/btcsuite/btcd/wire"
+	"github.com/btcsuite/btcwallet/chain/internal/rescan"
+	"github.com/lightninglabs/neutrino"
+	"github.com/lightninglabs/neutrino/banman"
+	"github.com/lightninglabs/neutrino/headerfs"
+)
+
+// Define variables for mocks
```
Comment (guggero) [inline chain/mocks_test.go:19]: nit: incomplete comments in several places of the file (missing punctuation). Also, this comment just repeats the code below and doesn't really add any useful information.

File: chain/mocks_test.go [hunk 5]
```diff
@@ -0,0 +1,152 @@
...
+)
+
+// Define static type checks
+var (
+	_ rescan.Interface     = (*mockRescanner)(nil)
+	_ NeutrinoChainService = (*mockChainService)(nil)
+)
+
+func newMockNeutrinoClient(t *testing.T,
+	opts ...func(*mockRescanner)) *NeutrinoClient {
```
Comment (guggero) [inline chain/mocks_test.go:36]: nit: add a newline after a multi-line function definition. We try to adhere to [`lnd`'s code formatting rules](https://github.com/lightningnetwork/lnd/blob/master/docs/code_formatting_rules.md) here as well, at least for new code.

File: chain/neutrino.go [hunk 6]
```diff
@@ -785,3 +782,17 @@ out:
 	close(s.dequeueNotification)
 	s.wg.Done()
 }
+
+// getNewRescanner injects the Rescanner constructor when called and defaults
+// to using neutrino.NewRescan when unspecified.
+func (s *NeutrinoClient) getNewRescanner() rescan.New {
```
Comment (guggero) [inline chain/neutrino.go]: I think this function should be passed in when creating the client. See my main comment with the proposed diff.

File: chain/neutrino_test.go [hunk 7]
```diff
@@ -76,3 +77,71 @@ func TestNeutrinoClientNotifyReceived(t *testing.T) {
...
+	err := nc.Start()
+	require.NoError(t, err)
+
+	// Launch the wanted number of goroutines, wait for them to finish and
+	// signal all done.
+	wg.Add(wantRoutines)
+	go func() {
+		defer close(done)
+		defer wg.Wait()
+		for i := 0; i < wantRoutines; i++ {
```
Comment (guggero) [inline chain/neutrino_test.go:130]: Very nice to have more test coverage for the concurrent code!

File: chain/neutrino.go [hunk 8]
```diff
@@ -77,6 +77,7 @@ type NeutrinoClient struct {
 	isRescan   bool
 
 	clientMtx sync.Mutex
+	rescanMtx sync.Mutex
```
Comment (guggero) [inline chain/neutrino.go:81]: Can you add a Godoc comment here describing what variables exactly this mutex is guarding?

File: chain/neutrino.go [hunk 9]
```diff
@@ -105,18 +105,25 @@ func (s *NeutrinoClient) Start() error {
...
 		s.enqueueNotification = make(chan interface{})
 		s.dequeueNotification = make(chan interface{})
 		s.currentBlock = make(chan *waddrmgr.BlockStamp)
 		s.quit = make(chan struct{})
 		s.started = true
+
+		// Go place a ClientConnected notification onto the queue.
 		s.wg.Add(1)
 		go func() {
+			defer s.wg.Done()
```
Comment (guggero) [inline chain/neutrino.go:118]: Nice catch!

Can you add an empty line after the `defer` call to visually separate it better from the `select` statement?

File: chain/internal/rescan/rescan.go [hunk 10]
```diff
@@ -18,7 +18,11 @@ type Interface interface {
 	Starter
 	Updater
 
+	// WaitForShutdown blocks until the underlying rescan object is shutdown.
```
Comment (guggero) [inline chain/internal/rescan/rescan.go:21]: This commit should be squashed with the commit that introduced the code. A PR should be structured in a way that explains to the reviewer how the pieces fit together, not what versions of changes each file went through during development. So things like renames or adding comments to code that is introduced in the same PR should always be squashed with the commit that introduces the code. Otherwise a reviewer needs to keep all different names in memory, which makes it harder.

File: chain/neutrino_test.go [hunk 11]
```diff
@@ -14,7 +14,8 @@ import (
 // can sequentially Start and Stop without errors or races.
 func TestNeutrinoClientSequentialStartStop(t *testing.T) {
 	var (
-		ctx, cancel   = context.WithTimeout(context.Background(), 1*time.Second)
+		ctx, cancel = context.WithTimeout(context.Background(),
```
Comment (guggero) [inline chain/neutrino_test.go:18]: nit: formatting of multi-line function call.

File: chain/neutrino.go [hunk 12]
```diff
@@ -797,16 +797,22 @@ out:
...
-	if s.newRescanner == nil {
-		s.newRescanner = func(ropts ...neutrino.RescanOption) rescan.Interface {
-			cs := &neutrino.RescanChainSource{
-				ChainService: s.CS.(*neutrino.ChainService),
-			}
-			return neutrino.NewRescan(cs, ropts...)
+func (s *NeutrinoClient) getNewRescanFunc() rescan.NewFunc {
+	if s.newRescanFunc == nil {
+		// Must cast CS as *neutrino.ChainService
+		cs := s.CS.(*neutrino.ChainService)
```
Comment (guggero) [inline chain/neutrino.go]: This cast can be avoided when we instead pass in the whole function that creates a rescan (see my diff).

File: chain/neutrino.go [hunk 13]
```diff
@@ -107,14 +107,12 @@ func (s *NeutrinoClient) Start() error {
 	s.clientMtx.Lock()
 	defer s.clientMtx.Unlock()
 	if !s.started {
-		// Reset the client state.
```
Comment (guggero) [inline chain/neutrino.go]: Why are we removing those comments again?

**Review by guggero — COMMENTED** [review]
Thank you for re-structuring the PR! I left a few suggestions for how to improve it even more for easier review.
But I was able to understand all the changes, nice work! Sorry it took so long to get to the first pass review.

I think we can further reduce the diff by passing in the `newRescanFunc` in the `NewNeutrinoClient`. That removes the need for any type casting or having two versions of the `cs` member around. See my diff with the proposed changes (might need some additional cleanup, this is just to get my idea across):

[pr-822.diff.txt](https://github.com/btcsuite/btcwallet/files/10031471/pr-822.diff.txt)

File: chain/neutrino.go (hunk 13 above)
Comment (MStreet3) [reply chain/neutrino.go]: I added these earlier when fixing the race condition in start/stop and removed them in this commit just to make the diff against master smaller, wasn't sure if they were useful enough to be kept.  I can add them back. 👍🏾

File: chain/internal/rescan/rescan.go (hunk 10 above)
Comment (MStreet3) [reply chain/internal/rescan/rescan.go:21]: noted, thanks

File: chain/neutrino.go [hunk 14]
```diff
@@ -356,6 +362,10 @@ func (s *NeutrinoClient) pollCFilter(hash *chainhash.Hash) (*gcs.Filter, error)
 func (s *NeutrinoClient) Rescan(startHash *chainhash.Hash, addrs []btcutil.Address,
 	outPoints map[wire.OutPoint]btcutil.Address) error {
 
+	// Obtain and hold the rescan mutex lock for the duration of the call.
+	s.rescanMtx.Lock()
```
Comment (guggero) [inline chain/neutrino.go:374]: Very nice and straightforward solution!

**Review by guggero — COMMENTED** [review]
Very nice, only nits left :tada: Thanks for all your work on this!

**Comment by guggero** [comment]
@ellemouton could you take a look at this as well please?

File: chain/neutrino.go (hunk 14 above)
Comment (MStreet3) [reply chain/neutrino.go:382]: Thanks 🙏🏾

**Review by chappjc — COMMENTED** [review]
The `rescanMtx` resolution seems fine, but this PR introduces some notable and breaking API changes and abstraction, which create some challenges and confusion for consumers.

The abstraction seems unnecessary, except for test stubbing, but even then I don't think the constructors and exported types need to change. Namely, the test code can and does set the fields directly with its mock stubs (without using the constructors), since e.g. `newMockNeutrinoClient` manually creates the `NeutrinoClient`, and the newly added `NewRescanFunc` isn't used.  Could the exported constructor, which consumers like btcwallet use, deal with setting up the rescanner fields from the provided chain service?

This is only from a cursory scan, so I apologize in advance if my assessment is off base, but I don't think this improves the API in its present state, and I suspect the goals of testing with a mock chain service can still be achieved without the API changes.

File: chain/neutrino.go [hunk 15]
```diff
@@ -45,20 +52,45 @@ type NeutrinoClient struct {
...
+	// shared mechanism.
 	clientMtx sync.Mutex
 }
 
 // NewNeutrinoClient creates a new NeutrinoClient struct with a backing
 // ChainService.
 func NewNeutrinoClient(chainParams *chaincfg.Params,
-	chainService *neutrino.ChainService) *NeutrinoClient {
+	chainService neutrinoChainService,
+	newRescan newRescanFunc) *NeutrinoClient {
```
[the remark this answers is not in the document]
Comment (MStreet3) [reply chain/neutrino.go:69]: I see your point about changing the NewNeutrinoClient constructor. It's feasible to let this constructor define the rescan constructor internally. 

I don't see an issue with exporting the neutrinoChainService interface. I left it private assuming all consumers would just use `*neutrino.ChainService` (I.e., no other concrete implementations exist or plan to exist).

[the remark this answers is not in the document]
Comment (chappjc) [reply chain/neutrino.go:69]: > I left it private assuming all consumers would just use `*neutrino.ChainService` (I.e., no other concrete implementations exist or plan to exist).

That's what I gathered.  In that case, I don't see a reason to use the interface in the constructor's input args.  Just changing the `CS` field type would suffice since the tests aren't using the constructor anyway. Even that is a breaking API change, but not as disruptive I think since that field probably shouldn't have been exported anyway.

[the remark this answers is not in the document]
Comment (MStreet3) [reply chain/neutrino.go:69]: Right right, let me give it a try. Would be good to reduce the surface area of the change.

**Comment by chappjc** [comment]
@MStreet3 Thanks for restoring the `NewNeutrinoClient` function signature in https://github.com/btcsuite/btcwallet/compare/a175d3fd326a898cf5cd4c16a01cd32860fbddd6..a6507c0ba3d9b62d563df9fb51c6a6c956f53edc.  That gives me great relief.  Ideally there would be no breaking changes, but I don't expect that `CS` field type change to have a great impact.

My only other comments are mainly stylistic, and that's not my place.

One strange (existing) thing I noticed in neutrino.go is that `s.scanning` is never (re)set to false, I think.  That seems to permanently affect the flow of `NotifyBlocks` and `NotifyReceived` if a rescan hand been done and completed at any point.  Does that seem intentional?  The multitude of undocumented `bool`s (`started`, `scanning`, `finished`, `isRescan`) are confusing.

**Comment by MStreet3** [comment]
> One strange (existing) thing I noticed in neutrino.go is that `s.scanning` is never (re)set to false, I think.  That seems to permanently affect the flow of `NotifyBlocks` and `NotifyReceived` if a rescan hand been done and completed at any point.  Does that seem intentional?  The multitude of undocumented `bool`s (`started`, `scanning`, `finished`, `isRescan`) are confusing.

I think that's intentional. `scanning` just means that the rescan goroutine is listening. Calls to update actually send some new options that trigger a "rescan". Once the rescan goroutine is running, it's not torn down except in calls to the Rescan method, but that always creates a new routine. I don't have enough context to advocate for or against the setup. This is why the fix for the seg fault here is intended be small. 

The Stop method of the neutrino client should stop the rescan goroutine but I don't think it's caused any issues yet to warrant a PR.

File: chain/rescan.go [hunk 16]
```diff
@@ -0,0 +1,42 @@
+package chain
+
+import "github.com/lightninglabs/neutrino"
+
+var _ rescanner = (*neutrino.Rescan)(nil)
+
+// updater is the interface that wraps the Update method of a rescan object.
+
+// Update targets a long-running rescan/notification client with updateable
```
Comment (guggero) [inline chain/rescan.go:9]: The Godoc comment for the `Update` method should be right above the method definition. So it's duplicated now, can just move this to replace what's on L14. Same for the `Start()` method of the `starter`.

File: chain/mocks_test.go [hunk 17]
```diff
@@ -0,0 +1,171 @@
...
+	// newRescanFunc returns a mockRescanner
+	newRescanFunc := func(ro ...neutrino.RescanOption) rescanner {
+		return &mockRescanner{
+			updateArgs: list.New(),
+		}
+	}
+
+	return &NeutrinoClient{
+		CS:        &mockChainService{},
+		newRescan: newRescanFunc,
```
Comment (guggero) [inline chain/mocks_test.go:41]: Ah, this works too, nice. Not breaking the interface is definitely a plus (though it wouldn't have mattered to our use case too much as we'd need to update `lnd` anyway).

File: chain/neutrino_test.go [hunk 18]
```diff
@@ -0,0 +1,190 @@
...
+	// channel.
+	executeCalls := func(n int) <-chan struct{} {
+		var (
+			done = make(chan struct{})
+			wg   sync.WaitGroup
+		)
+
+		go func() {
+			defer close(done)
+			defer wg.Wait()
```
Comment (guggero) [inline chain/neutrino_test.go:157]: I think the `wg.Wait()` should come before the `close(done)`, otherwise the `select` below will return even though the wait might have still blocked. Maybe the wait should be right after the loop instead?

File: chain/neutrino.go [hunk 19]
```diff
@@ -46,6 +52,13 @@ type NeutrinoClient struct {
 	finished   bool
 	isRescan   bool
 
+	// The clientMtx synchronizes access to the state variables of the client.
+	// TODO(mstreet3): Currently the clientMtx synchronizes access to the
```
Comment (guggero) [inline chain/neutrino.go:56]: nit: add an empty comment line before a TODO so it stands out a bit more.

**Review by guggero — COMMENTED** [review]
Nice update, this is almost ready IMO :tada:

File: chain/neutrino_test.go (hunk 18 above)
Comment (MStreet3) [reply chain/neutrino_test.go:157]: defer statements are executed from the bottom up, we wait and then close done.

File: chain/mocks_test.go [hunk 20]
```diff
@@ -0,0 +1,171 @@
...
+
+// mockRescanner is a mock implementation of a rescanner interface for use in
+// tests.  Only the Update method is implemented.
+type mockRescanner struct {
+	updateArgs *list.List
+}
+
+func (m *mockRescanner) Start() <-chan error {
+	errs := make(chan error)
+	return errs
```
Comment (chappjc) [inline chain/mocks_test.go:53]: `return make(chan error)`?

File: chain/neutrino_test.go [hunk 21]
```diff
@@ -0,0 +1,209 @@
...
+	"github.com/btcsuite/btcd/wire"
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+// TestNeutrinoClientSequentialStartStop ensures that the client
+// can sequentially Start and Stop without errors or races.
+func TestNeutrinoClientSequentialStartStop(t *testing.T) {
+	var (
+		timeout      = time.After(1 * time.Second)
```
Comment (chappjc) [inline chain/neutrino_test.go:19]: CI can be very laggy, almost as if the VMs randomly pause, but if 1sec works, ok.  I'd be surprised if that's not often too short.  Would it hurt to go with 5 or even 10 seconds?  It only slows a test that would fail, not a passing one.

File: chain/neutrino_test.go [hunk 22]
```diff
@@ -0,0 +1,209 @@
...
+
+	// Define closures to wrap desired neutrino client method calls.
+
+	// callRescan calls the Rescan() method and asserts it completes
+	// with no errors. Rescan() is called with the hash of an empty header
+	// on each call.
+	var (
+		emptyHeader = &wire.BlockHeader{}
+		startHash   = emptyHeader.BlockHash()
+	)
```
Comment (chappjc) [inline chain/neutrino_test.go:123]: You'd be fine with just `startHash := new(wire.BlockHeader).BlockHash()` and no `emptyHeader` declared, but NBD.

**Review by chappjc — COMMENTED** [review]
LGTM, just a few mostly style related comments.
Have yet to actually test in our app, but I see no obvious issues with the interface unchanged.

File: chain/chainservice.go [hunk 23]
```diff
@@ -0,0 +1,40 @@
...
+	GetBlockHeight(*chainhash.Hash) (int32, error)
+	BestBlock() (*headerfs.BlockStamp, error)
+	GetBlockHash(int64) (*chainhash.Hash, error)
+	GetBlockHeader(*chainhash.Hash) (*wire.BlockHeader, error)
+	IsCurrent() bool
+	SendTransaction(*wire.MsgTx) error
+	GetCFilter(chainhash.Hash, wire.FilterType,
+		...neutrino.QueryOption) (*gcs.Filter, error)
+	GetUtxo(...neutrino.RescanOption) (*neutrino.SpendReport, error)
+	BanPeer(string, banman.Reason) error
```
[the remark this answers is not in the document]
Comment (MStreet3) [reply chain/chainservice.go:28]: yes, so the first time I implemented this it was much slimmer, but I saw that this created a failure in LND.  This is because LND has some code that is directly accessing the `CS` field of a `NeutrinoClient`.  The consumer in LND expected the `CS` field to be the single `*neutrino.ChainService` concrete implementation, but in reality it was the slim interface.  So to be able to allow LND to update the version of `btcwallet` with this change I had to expose EVERY public method of `*neutrino.ChainService` event though a `NeutrinoClient` _only_ uses a few of the methods.

[the remark this answers is not in the document]
Comment (chappjc) [reply chain/chainservice.go:28]: Ohhhh, ok.  That's interesting.

I'd just note that lnd can assert that CS satisfies an even broader interface itself (the assertion applies to the underlying type, which can have more methods).  It seems like the lnd-btcwallet relationship is quite tight.  This partly explains why `CS` is even exported.

File: chain/rescan.go [hunk 24]
```diff
@@ -0,0 +1,41 @@
...
+	starter
+	updater
+
+	// WaitForShutdown blocks until the underlying rescan object is shutdown.
+	// Close the quit channel before calling WaitForShutdown.
+	WaitForShutdown()
+}
+
+// updater is the interface that wraps the Update method of a rescan object.
+
```
Comment (guggero) [inline chain/rescan.go:20]: nit: extra newline here and below.

File: chain/neutrino_test.go [hunk 25]
```diff
@@ -0,0 +1,219 @@
...
+	timeout := time.After(maxDur)
+	select {
+	case <-timeout:
+		t.Fatal("timed out")
+	case <-executeCalls(wantMsgs):
+		// Ensure that exactly wantRoutines number of calls were made
+		// by counting the results on the message channel.
+		close(msgCh)
+		for str := range msgCh {
+			assert.NotNil(t, str)
```
Comment (guggero) [inline chain/neutrino_test.go:212]: A string cannot be nil, so the `Contains` below is enough IMO.

**Review by guggero — APPROVED** [review]
Very nice, LGTM :tada:

**Review by guggero — APPROVED** [review]
Thanks a lot for all the quick updates on this. LGTM :tada: 
Before we merge this, can you please update (or create?) the PR on the `lnd` side to make sure all neutrino integration tests still pass?

**Comment by MStreet3** [comment]
@guggero the corresponding LND PR with updated btcwallet is here: https://github.com/lightningnetwork/lnd/pull/7049

**Review by ellemouton — APPROVED** [review]
Very nice! Love the new abstractions that make things way more testable. Great job!

**Comment by guggero** [comment]
@MStreet3 can you do a rebase please?
Also, @chappjc could I ask you for another round of review please, since you did a first round a while ago.

**Review by chappjc — APPROVED** [review]
Still builds and runs fine in my use case.

With limited familiarity with btcwallet's code, the atomicity changes look fine too.  I don't see any lock ordering pitfalls that could lead to deadlock, but it's a risk of nested locking.

I think see some ancient data races on the `rescanQuit` field in the notification handlers like `onBlockConnected`, but that's unrelated to the issue being solved in this PR.
