### PR TITLE
Stop wallet and close wallet DB on interrupt.

### LINKED ISSUE #282: calling wallet.Stop() at application exit results in an error
It doesn't happen 100% of the times, so probably a race condition somewhere.

```
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xb code=0x1 addr=0x18 pc=0x43f37b5]

	goroutine 51 [running]:
			github.com/btcsuite/bolt.(*freelist).rollback(0x0, 0x77)
	go/src/github.com/btcsuite/bolt/freelist.go:144 +0x35
			github.com/btcsuite/bolt.(*Tx).rollback(0xc20801ec30)
	go/src/github.com/btcsuite/bolt/tx.go:223 +0x5c
			github.com/btcsuite/bolt.func·010()
	go/src/github.com/btcsuite/bolt/db.go:497 +0x38
			github.com/btcsuite/bolt.(*Tx).write(0xc20801ec30, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/tx.go:428 +0x350
			github.com/btcsuite/bolt.(*Tx).Commit(0xc20801ec30, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/tx.go:176 +0x47c
			github.com/btcsuite/bolt.(*DB).Update(0xc208035380, 0xc2183e1d10, 0x0, 0x0)
	go/src/github.com/btcsuite/bolt/db.go:512 +0x169
					github.com/btcsuite/btcwallet/walletdb/bdb.(*namespace).Update(0xc2080c34e0, 0xc2080c33a0, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:348 +0x66
				github.com/btcsuite/btcwallet/waddrmgr.(*Manager).SetSyncedTo(0xc208034680, 0xc2080cc930, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/waddrmgr/sync.go:221 +0x37a
				github.com/btcsuite/btcwallet/wallet.(*Wallet).syncWithChain(0xc2080daa20, 0x0, 0x0)
	go/src/github.com/btcsuite/btcwallet/wallet/wallet.go:433 +0x40f
				github.com/btcsuite/btcwallet/wallet.func·001(0xc2080daa20)
	go/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:32 +0x2b
	created by github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications
	go/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:42 +0x438
```

### LINKED ISSUE #283: wtxmgr: panic on interrupt
This happens sometimes when btcsim is interrupted. Will try to list the exact steps to repro, maybe consider it low priority until then.

    unexpected fault address 0x7fc2277c6068
    fatal error: fault
    [signal 0xb code=0x1 addr=0x7fc2277c6068 pc=0x82ee1d]

    goroutine 37 [running]:
    runtime.gothrow(0xaac260, 0x5)
            /usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2095490b0 sp=0xc209549098
    runtime.sigpanic()
            /usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc209549100 sp=0xc2095490b0
    github.com/btcsuite/bolt.func·009(0x5, 0x7fc22c038500)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/bolt/cursor.go:318 +0x5d fp=0xc209549188 sp=0xc209549100
    sort.Search(0xb, 0xc209549240, 0x7)
            /usr/local/go/src/sort/search.go:66 +0x59 fp=0xc2095491b8 sp=0xc209549188
    github.com/btcsuite/bolt.(*Cursor).nsearch(0xc2098ea140, 0xf0926c, 0x2, 0x2)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/bolt/cursor.go:319 +0x166 fp=0xc209549278
    github.com/btcsuite/bolt.(*Cursor).seek(0xc2098ea140, 0xf0926c, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/bolt/cursor.go:152 +0x122 fp=0xc2095493d0 sp=0xc209549370
    github.com/btcsuite/bolt.(*Bucket).Bucket(0xc20883eac0, 0xf0926c, 0x2, 0x2, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/bolt/bucket.go:111 +0x1df fp=0xc2095494c0 sp=0xc2095493d0
    github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).Bucket(0xc20883eac0, 0xf0926c, 0x2, 0x2, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:77 +0x58 fp=0xc2095494f8 sp=0xc2095494c0
    github.com/btcsuite/btcwallet/wtxmgr.existsRawUnminedInput(0x7fc22e8944e0, 0xc20883eac0, 0x7fc2277ab578, 0x24, 0x7ffffb67, 0x0, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/db.go:1185 +0x73 fp=0xc209549548 sp=0xc2095494f8
    github.com/btcsuite/btcwallet/wtxmgr.func·017(0x7fc2277ab578, 0x24, 0x7ffffb67, 0x7fc2277ab59c, 0x24, 0x7ffffb43, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/tx.go:837 +0x169 fp=0xc2095495f0 sp=0xc209549548
    github.com/btcsuite/bolt.(*Bucket).ForEach(0xc20883eb00, 0xc209d8e6f0, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/bolt/bucket.go:356 +0x1dd fp=0xc2095496a8 sp=0xc2095495f0
    github.com/btcsuite/btcwallet/walletdb/bdb.(*bucket).ForEach(0xc20883eb00, 0xc209d8e6f0, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/walletdb/bdb/db.go:130 +0x44 fp=0xc2095496e0 sp=0xc2095496a8
    github.com/btcsuite/btcwallet/wtxmgr.(*Store).balance(0xc2083c6300, 0x7fc22e8944e0, 0xc20883eac0, 0x3ef00000001, 0xc20883eac0, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/tx.go:846 +0x2a6 fp=0xc209549a88 sp=0xc2095496e0
    github.com/btcsuite/btcwallet/wtxmgr.func·016(0x7fc22e8944e0, 0xc20883eac0, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/tx.go:812 +0x80 fp=0xc209549ae0 sp=0xc209549a88
    github.com/btcsuite/btcwallet/wtxmgr.scopedView(0x7fc22e894470, 0xc2080cb580, 0xc209549c88, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/db.go:1385 +0x1dd fp=0xc209549c58 sp=0xc209549ae0
    github.com/btcsuite/btcwallet/wtxmgr.(*Store).Balance(0xc2083c6300, 0x3ef00000001, 0xc208162180, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wtxmgr/tx.go:814 +0x8b fp=0xc209549cb8 sp=0xc209549c58
    github.com/btcsuite/btcwallet/wallet.(*Wallet).notifyBalances(0xc2080be000, 0xc2000003ef)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:218 +0x68 fp=0xc209549d40 sp=0xc209549cb8
    github.com/btcsuite/btcwallet/wallet.(*Wallet).addRelevantTx(0xc2080be000, 0xc2081af4d0, 0xc20850fa40, 0x0, 0x0)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:205 +0x1f9 fp=0xc209549ea8 sp=0xc209549d40
    github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc2080be000)
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/chainntfns.go:48 +0x3b0 fp=0xc209549fd8 sp=0xc209549ea8
    runtime.goexit()
            /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc209549fe0 sp=0xc209549fd8
    created by github.com/btcsuite/btcwallet/wallet.(*Wallet).Start
            /home/tuxcanfly/Work/conformal/src/github.com/btcsuite/btcwallet/wallet/wallet.go:304 +0x19d

### PR DESCRIPTION
**Pull request by jrick**
This corrects and simplifies the shutdown logic for interrupts, the
walletrpc.WalletLoaderService/CloseWallet RPC, and the legacy stop RPC
by both stopping all wallet processes and closing the wallet database.
It appears that this behavior broke as part of the wallet package
refactor, causing occasional nil pointer panics and memory faults when
closing the wallet database with active transactions.

Fixes #282.

Fixes #283.

### CODE REVIEW

File: wallet/loader.go [hunk 1]
```diff
@@ -240,6 +244,33 @@ func (l *Loader) LoadedWallet() (*Wallet, bool) {
...
+	defer l.mu.Unlock()
+	l.mu.Lock()
+
+	if l.wallet == nil {
+		return ErrNotLoaded
+	}
+
+	l.wallet.Stop()
+	l.wallet.WaitForShutdown()
+	// TODO: Closing the wallet database really should be done by Stop, but
```
Comment (davecgh) [inline wallet/loader.go]: As discussed in IRC, it probably makes sense to keep the database close here in the loader since the caller might want to use a different backend and so the database needs to be passed into the wallet package like it is now in order to support that.

If the wallet package did the open it would be tied to whatever the wallet package wanted to use taking away the caller's flexibility.

**Comment by davecgh** [comment]
Reads well.  I'm testing it out now.

File: wallet/loader.go (hunk 1 above)
Comment (jrick) [inline wallet/loader.go]: Agree. will remove this comment.

**Comment by davecgh** [comment]
Everything works well.  I tested ctrl+C before and after load takes place as well as in the middle of a rescan.  I also tested sending a stop command via `btcctl` under the same circumstances.  The shutdown completed as expected and the rescan commenced at the expected block on reload in all cases.

OK
